spring:
  application:
    name: bpmn-analytics
  profiles:
    active: local # Профиль по умолчанию

---
# Общие настройки (для всех профилей)
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  charset:
    console: UTF-8
  file:
    charset: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.example.bpmnanalytics: DEBUG
    org.camunda: INFO
    org.elasticsearch: INFO

---
spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: http://localhost:9200
  jvm:
    options: -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
elasticsearch:
  url: http://localhost:9200

camunda:
  rest:
    url: http://localhost:8080/engine-rest

---
spring:
  config:
    activate:
      on-profile: docker
  elasticsearch:
    uris: http://elasticsearch:9200

elasticsearch:
  url: http://elasticsearch:9200

camunda:
  rest:
    url: http://camunda:8080/engine-rest
